on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://dutymachine/weixin-archive-action:latest
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
